# The base URL for the site.
baseURL = 'https://vetle.dev'
# The title of the site.
title = "vetle.dev"
# Enable Git info › https://gohugo.io/methods/page/gitinfo/
enableGitInfo = true
# The default content language.
defaultContentLanguage = "en"
# Whether the default content language is in a subdirectory.
defaultContentLanguageInSubdir = false
# Whether the site has CJK language (Chinese, Japanese, Korean).
hasCJKLanguage = false

# Pagination settings.
[pagination]
  pagerSize = 5

# Make sure to include JSON output to support the search functionality.
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Import the theme.
[module]
  [[module.imports]]
    path = "github.com/geekifan/hugo-theme-chirpy"