# Code highlighting settings.
[highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  tabWidth = 4
  wrapperClass = 'highlight'

[goldmark.parser]
  wrapStandAloneImageWithinParagraph = false

[goldmark.parser.attribute]
  block = true
  title = true

[goldmark.renderer]
  unsafe = true