# --- CONFIG ---
baseURL = "https://vetle.dev"
languageCode = "en-us"
title = "Vetle's Tech Chronicles"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
  pagerSize = 5

# -- MARKUP ---
[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 2

    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4

# --- PARAMS ---
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = false
    description = "A blog about technology, tutorials, and my thoughts."
    favicon = "/favicon.ico"

    [params.colorScheme]
        default = "auto"
        toggle = true
        
    [params.imageProcessing.cover]
        enabled = true

    [params.imageProcessing.content]
        enabled = true

    [params.sidebar]
        subtitle = "Vetle Kise | Senior Cloud Engineer @ Sopra Steria"
        compact = false
        
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.png" 

    [params.article]
        headingAnchor = true
        toc = true
        readingTime = true
        wordCount = true
    
    [params.footer]
        since = 2025
        # customText = ""

# --- MENU ---
[[menu.social]]
    name = "GitHub"
    url = "https://github.com/vetlekise"
    weight = 10
    [menu.social.params]
        icon = "brand-github"

[[menu.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/vetlekise"
    weight = 30
    [menu.social.params]
        icon = "brand-linkedin"

# --- HOMEPAGE WIDGETS ---
[[params.widgets.homepage]]
    type = "search"

[[params.widgets.homepage]]
    type = "archives"
    [params.widgets.homepage.params]
        limit = 5

[[params.widgets.homepage]]
    type = "categories"
    [params.widgets.homepage.params]
        limit = 10

[[params.widgets.homepage]]
    type = "tag-cloud"
    [params.widgets.homepage.params]
        limit = 20

# --- POST PAGE WIDGETS ---
[[params.widgets.page]]
    type = "toc"

## -- PERMALINKS ---
[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100
    [[related.indices]]
        name = "categories"
        weight = 200