# --- BASE CONFIG ---
baseURL = "https://vetle.dev"
languageCode = "en-us"
title = "vetle.dev"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
  pagerSize = 5

# --- THEME CONFIG ---
[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    description = "A blog about technology, tutorials, and my thoughts."
    favicon = "/favicon.ico"

    [params.sidebar]
        subtitle = "Senior Cloud Engineer @ Sopra Steria"
        compact = false
        
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.png" 

    [params.article]
        toc = true
        readingTime = true
        wordCount = true

# --- MAIN NAVIGATION MENU ---
[[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 30

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 40

# --- SOCIAL ICONS MENU ---
[[menu.social]]
    name = "GitHub"
    url = "https://github.com/vetlekise"
    weight = 10
    [menu.social.params]
        icon = "brand-github"

[[menu.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/vetlekise"
    weight = 30
    [menu.social.params]
        icon = "brand-linkedin"

# --- HOMEPAGE WIDGETS ---
[[params.widgets.homepage]]
    type = "search"

[[params.widgets.homepage]]
    type = "archives"
    [params.widgets.homepage.params]
        limit = 5

[[params.widgets.homepage]]
    type = "categories"
    [params.widgets.homepage.params]
        limit = 10

[[params.widgets.homepage]]
    type = "tag-cloud"
    [params.widgets.homepage.params]
        limit = 20

# --- POST PAGE WIDGETS ---
[[params.widgets.page]]
    type = "toc"

# --- OUTPUT FORMATS ---
[outputs]
  search = ["HTML", "JSON"]